### ISSUE TITLE
catshop app进入容器后是还有命令？cd /app/commerce

### ISSUE THREAD

**Issue by ken0709** [weeshop/WeeShop#10]
###进入docker容器
docker-compose exec server bash -T
这句没问题

###进入容器后，在容器内继续运行下面的命令
**这里是有命令？**

根据安装文件前面一切顺利，在

> cd /app/commerce

报错了，ls 查询下没有commerce 文件
![screen shot 2018-11-18 at 2 52 54 pm](https://user-images.githubusercontent.com/13581655/48669566-296a4780-eb42-11e8-8a01-9cc94d29f344.png)

**Comment by solody** [comment]
文档写错了，应该是 cd /app

**Comment by solody** [comment]
[https://github.com/catworking/catshop/commit/153fab84db41e7829418689d9788cdd658ac8975](https://github.com/catworking/catshop/commit/153fab84db41e7829418689d9788cdd658ac8975)
