### ISSUE TITLE
weeshop docker安装出现的问题

### ISSUE THREAD

**Issue by NineDfish** [weeshop/WeeShop#11]
composer install 
drupal/core 每次都是安装到50%
![Screen Shot 2019-07-31 at 4 02 24 PM](https://user-images.githubusercontent.com/27683840/62195230-1d5fa680-b3ae-11e9-8401-1a74bfe5d346.png)
实例安装报错
![Screen Shot 2019-07-31 at 4 01 36 PM](https://user-images.githubusercontent.com/27683840/62195275-38cab180-b3ae-11e9-8a1c-7d30fb33e615.png)
哪里出得问题

**Comment by solody** [comment]
composer install我没有试过有这样的问题，你加上 -vvv 看看原因，一般来说，下载没有成功的话，你是跑不起安装命令的。

安装时的报错，是因为git submodule管理的代码没有下载，在安装之前，先运行

git submodule init
git submodule update

这两条代码会拉取 git 子库代码。因为还是开发阶段，所以有的模块我暂时没有用composer管理。

**Comment by NineDfish** [comment]
server container 根目录运行 git init / git submodule / git submodule update, 安装实例 命令 跑 结果还是红色error.
是我执行git 路径错了么？
