### ISSUE TITLE
安装 过程2个大问题，

### ISSUE THREAD

**Issue by leehonleon** [weeshop/WeeShop#14]

**Comment by nixecn** [comment]
php compose 出现这问题
[ERROR] Configuration objects provided by product_search have unmet dependencies: search_api.index.product_search
         (field.storage.commerce_product_variation.attribute_color,
         field.storage.commerce_product_variation.attribute_size, enhanced_product)

**Comment by nixecn** [comment]
[root@instance-home WeeShop]# git submodule update
Cloning into 'commerce/web/modules/custom/account'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:solody/account.git' into submodule path 'commerce/web/modules/custom/account' failed

**Comment by nixecn** [comment]
Executing command (/app): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.6.5 (2018-05-04 11:44:59) with PHP 7.2.8 on Linux / 3.10.0-1062.1.2.el7.x86_64
Do not run Composer as root/super user! See https://getcomposer.org/root for details

**Comment by nixecn** [comment]
最后访问网站时 ，只显示一个输入用户名密码的界面。

**Comment by saonian** [comment]
`Drupal\Component\Plugin\Exception\PluginNotFoundException: The "user_role" entity type does not exist. `
我安装过程填写数据库信息确认后，就出现上述错误了。
请问该如何解决

**Comment by solody** [comment]
大家好，今天会出一个预览版本，会解决这些安装问题

**Comment by solody** [comment]
https://github.com/weeshop/WeeShop/releases/tag/1.0.0-beta2 请使用新版本，参考新的readme.md文档进行安装。

**Comment by solody** [comment]
https://github.com/weeshop/WeeShop/releases/tag/1.0.0-beta2 请使用新版本，参考新的readme.md文档进行安装。
