### ISSUE TITLE
开发起不来。。。。

### ISSUE THREAD

**Issue by jay763190097** [weeshop/WeeShop#15]
![深度截图_选择区域_20191123103316](https://user-images.githubusercontent.com/16317178/69471676-ebe76c80-0ddc-11ea-9fc9-0e2fef97c395.png)
![深度截图_选择区域_20191123103329](https://user-images.githubusercontent.com/16317178/69471678-f0ac2080-0ddc-11ea-81b9-413de687ddad.png)
![深度截图_选择区域_20191123103340](https://user-images.githubusercontent.com/16317178/69471679-f3a71100-0ddc-11ea-9686-41c94d011656.png)
![深度截图_选择区域_20191123103402](https://user-images.githubusercontent.com/16317178/69471680-f6a20180-0ddc-11ea-8e5b-11603394d52e.png)
文档是不是需要更新了

**Comment by solody** [comment]
https://github.com/weeshop/WeeShop/releases/tag/1.0.0-beta2 已经发布了新版本，改进了安装方式，并且更新了文档
