### ISSUE TITLE
ERROR: Error: image catshop/catshop:latest not found

### ISSUE THREAD

**Issue by wubuyun** [weeshop/WeeShop#2]
sudo docker-compose up
Pulling drupal (registry.cn-hangzhou.aliyuncs.com/catshop/catshop:latest)...
Pulling repository registry.cn-hangzhou.aliyuncs.com/catshop/catshop
ERROR: Error: image catshop/catshop:latest not found

**Comment by 372572571** [comment]
catshop/docker-compose.yml 
    image: registry.cn-hangzhou.aliyuncs.com/catshop/catshop:latest
modify
    image: edwinkent/catshop

**Comment by wubuyun** [comment]
c1a55c6375b5: Pull complete
8181cde51c65: Pull complete
Digest: sha256:691c55aabb3c4e3b89b953dd2f022f7ea845e5443954767d321d5f5fa394e28c
Status: Downloaded newer image for mysql:latest
Creating catshopmaster_db_1
Creating catshopmaster_drupal_1
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost

ERROR: for drupal  Cannot start service drupal: driver failed programming external connectivity on endpoint catshopmaster_drupal_1 (457594bd6ea8b536e32ddbe6402d863c03154da3b870a449b380771a448d41e5): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by solody** [comment]
I'm planing to fix this problem.
