### ISSUE TITLE
Error: image catshop/catshop:latest not found

### ISSUE THREAD

**Issue by 372572571** [weeshop/WeeShop#3]
Error: image catshop/catshop:latest not found？
如何解决？

**Comment by 372572571** [comment]
[ERROR] Configuration directory: <em class="placeholder">sync</em>:                                                    
                                                                                                                        
         An automated attempt to create the directory <em class="placeholder">../config/sync</em> failed, possibly due  
         to a permissions problem. To proceed with the installation, either create the directory and modify its         
         permissions manually or ensure that the installer has the permissions to create it automatically. For more     
         information, see INSTALL.txt or the <a href="https://www.drupal.org/server-permissions">online handbook</a>.   
                                                                                                                        
         File system: Writable (<em>public</em> download method)                                                        
                                                                                                                        
         Array                                                                                                          
                                                                                                                        
         Settings file: The <em class="placeholder">Settings file</em> is not writable.                                 
                                                                                                                        
         The CatShop installer requires write permissions to <em class="placeholder">./sites/default/settings.php</em>  
         during the installation process. The <a href="https://www.drupal.org/server-permissions">webhosting            
         issues</a> documentation section offers help on this and other topics.

**Comment by solody** [comment]
我正准备要解决此问题，请参考 [https://github.com/catworking/catshop/issues/3](https://github.com/catworking/catshop/issues/3)
