### ISSUE TITLE
Cenos7 挂在权限问题

### ISSUE THREAD

**Issue by G3792274** [weeshop/WeeShop#9]
见图。
![11](https://user-images.githubusercontent.com/19231863/41418538-7c9d0988-7022-11e8-9158-8050123c491d.jpg)

**Comment by G3792274** [comment]
数据库连接问题

![11](https://user-images.githubusercontent.com/19231863/41418649-b952d4e8-7022-11e8-9cfb-2aca5681ada6.jpg)

**Comment by G3792274** [comment]
![1111](https://user-images.githubusercontent.com/19231863/41423021-dc18ea62-702c-11e8-8f13-9f07fa13acf0.jpg)


![2222](https://user-images.githubusercontent.com/19231863/41423023-dde38942-702c-11e8-9db4-5a2882e513be.jpg)

**Comment by solody** [comment]
感谢关注，已知 windows下docker会有目录权限问题。
第二版很快会出来。

**Comment by solody** [comment]
重构版已发布，但成熟，有兴趣可以试试
